// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6YScERJefk6F4T3xqWA8jgNeYKg2An60',
    appId: '1:505038605485:android:e17f6762e1b9bdbb8a0a24',
    messagingSenderId: '505038605485',
    projectId: 'carsharingdatabase-f3ff2',
    storageBucket: 'carsharingdatabase-f3ff2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQvHuHnw_RSONjaQBZD_vAu0Cydmc3JEw',
    appId: '1:505038605485:ios:49ad0f40b8323ab38a0a24',
    messagingSenderId: '505038605485',
    projectId: 'carsharingdatabase-f3ff2',
    storageBucket: 'carsharingdatabase-f3ff2.appspot.com',
    iosClientId: '505038605485-fh9o9vssqqjgrgh2l7ggn0kr0nei0oun.apps.googleusercontent.com',
    iosBundleId: 'com.classcar.clientAppClasscar',
  );
}
